### ISSUE TITLE
How could sockexec run shell script as root?

### ISSUE THREAD

**Issue by yorkane** [jprjr/sockexec#12]
I've try configs as below, but as I run `prog({'ngxin','-s', 'reload'})` in openresty worker
It threw `permission denied` error.
Could you please fix it?

cat > /etc/systemd/system/sockexec.service <<eof
[Unit]
description=sockexec
After=network.target

[Service]
ExecStart=/usr/local/openresty/nginx/docker/bin/sockexec /tmp/exec.sock
User=root

[Install]
WantedBy=multi-user.target
eof

**Comment by jprjr** [comment]
There's nothing stopping `sockexec` from running programs as root. What's likely happening is your default umask is `022`, so the socket is being created with `755` permissions - meaning only the root user can write data into it. And nginx is probably running as not root.

You can edit the service script to specify a umask, but I always have a hard time getting my umasks straight since it's kinda backwards from how we usually think of file permissions.

I just pushed up version 3.1.0 which lets you specify the file creation mode with `-M`. Additionally, I changed the default permissions to `660` - so the owner and group can read/write.

After updating, I'd suggest changing the group of the `sockexec` process to something other than root, and making sure your openresty process is in that same group.

**Comment by yorkane** [comment]
Thank you so much, I am really appreciate!

I will try it later.
